spring:
  application:
    name: activity-service

  data:
    mongodb:
      url: mongodb://localhost:27017/Fitnessactivity
      database: Fitnessactivity

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/